apiVersion: v1
kind: Service
metadata:
  name: python-sample
  labels:
    app: python-sample
spec:
  ports:
    - name: http-web
      port: 80
      targetPort: 5000
  selector:
    app: python-sample
