{{ $replica := .Values.stage.rb88.replica.wallet }}
{{ $image := .Values.stage.rb88.image.wallet }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service-v1
  labels:
    app: wallet-service
    version: v1
spec:
  replicas: {{ $replica }}
  selector:
    matchLabels:
      app: wallet-service
      version: v1
  template:
    metadata:
      labels:
        app: wallet-service
        version: v1
    spec:
      containers:
        - name: wallet-service
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: wallet-service
            - name: activeProfiles
              valueFrom:
                configMapKeyRef:
                  key: activeProfiles
                  name: wallet-service
            - name: logstashUrl
              valueFrom:
                configMapKeyRef:
                  key: logstashUrl
                  name: wallet-service
          resources:
            limits:
              memory: "12Gi"
            requests:
              memory: "8Gi"
          image: {{ $image }}
          imagePullPolicy: Always
