{{ $port := .Values.common.port.wallet }}

apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  labels:
    app: wallet-service
spec:
  ports:
    - name: http-web
      port: 80
      targetPort: {{ $port }}
  selector:
    app: wallet-service
