apiVersion: v1
kind: ConfigMap
metadata:
  name: java-sample
  labels:
    app: java-sample
data:
  TZ: Asia/Taipei
  activeProfiles: k8s
  first: Daniel
  last: Liu
  application.yml: |-
    spring:
      profiles: k8s
    custom:
      key: in-configmap
