version: '3'

services:
  python-sample:
    image: taiwanbackendgroup/python-sample:1.0.0
    volumes:
      - ./log:/python-sample/log
    environment:
      - first=Vincent
      - last=Huang
    ports:
      - "5000:5000"
    networks:
      - default

  ### cache ###
  redis:
    image: redis:${REDIS_VERSION}
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - default

  ### database ###
  mysql: # root/123456
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD="123456"
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default:
